--- #YAML:1.0
name:               WWW-Salesforce
version:            0.15
abstract:           this class provides a simple abstraction layer between SOAP::Lite and Salesforce.com.
author:
    - Chase Whitener <cwhitener@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Crypt::SSLeay:  0.56
    SOAP::Lite:     0.68
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
